version: '3.7'

services:
  db:
    container_name: craftbid_db
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: craftbid_db
    ports:
      - "8001:5432"
