on:
  push:
    branches:
      - master

env:
  SPRING_DATA_SOURCE_URL_ENV: ${{ secrets.SPRING_DATA_SOURCE_URL }}
  SPRING_DATA_SOURCE_USERNAME_ENV: ${{ secrets.SPRING_DATA_SOURCE_USERNAME }}
  SPRING_DATA_SOURCE_PASSWORD_ENV: ${{ secrets.SPRING_DATA_SOURCE_PASSWORD }}
  SPRING_TOKEN_KEY_ENV: ${{ secrets.SPRING_TOKEN_KEY }}
          
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      
      - name: Replace SPRING_DATA_SOURCE_URL_PLACEHOLDER in application.properties
        run: |
          sed "s|SPRING_DATA_SOURCE_URL_PLACEHOLDER|${SPRING_DATA_SOURCE_URL_ENV}|g" application.properties > application.properties.temp
          mv application.properties.temp application.properties
        working-directory: src/main/resources
      
      - name: Replace SPRING_DATA_SOURCE_USERNAME_PLACEHOLDER in application.properties
        run: |
          sed "s|SPRING_DATA_SOURCE_USERNAME_PLACEHOLDER|${SPRING_DATA_SOURCE_USERNAME_ENV}|g" application.properties > application.properties.temp
          mv application.properties.temp application.properties
        working-directory: src/main/resources
      
      - name: Replace SPRING_DATA_SOURCE_PASSWORD_PLACEHOLDER in application.properties
        run: |
          sed "s|SPRING_DATA_SOURCE_PASSWORD_PLACEHOLDER|${SPRING_DATA_SOURCE_PASSWORD_ENV}|g" application.properties > application.properties.temp
          mv application.properties.temp application.properties
        working-directory: src/main/resources
      
      - name: Replace SPRING_TOKEN_KEY_PLACEHOLDER in application.properties
        run: |
          sed "s|SPRING_TOKEN_KEY_PLACEHOLDER|${SPRING_TOKEN_KEY_ENV}|g" application.properties > application.properties.temp
          mv application.properties.temp application.properties
        working-directory: src/main/resources


    
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Set the Java version to 17
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package -DskipTests=true

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
  
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 450.0.0'      
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true
        
      - name: Deploy to App Engine
        run: gcloud app deploy
