on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Set the Java version to 17
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean install

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
  
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 450.0.0'      
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true
        
      - name: Deploy to App Engine
        run: gcloud app deploy target/craftbid-0.0.1-SNAPSHOT.jar
